apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api-vs
spec:
  hosts:
  - {{ .Values.hosts.api }}
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: api-http
    protocol: HTTP
  resolution: DNS
---
