apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: id-se
spec:
  hosts:
  - {{ .Values.hosts.idp }}
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: idp-http
    protocol: HTTP
  resolution: DNS
---
