apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
spec:
  hosts:
  - {{ .Values.hosts.web }}
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /catalog/
    - uri:
        prefix: /catalog
    route:
    - destination:
        host: catalog
        port:
          number: 5002
  - match:
    - uri:
        prefix: /cart/
    - uri:
        prefix: /cart
    route:
    - destination:
        host: cart
        port:
          number: 5003
  - match:
    - uri:
        prefix: /inventory/
    - uri:
        prefix: /inventory
    route:
    - destination:
        host: inventory
        port:
          number: 5004
  - match:
    - uri:
        prefix: /rating/
    - uri:
        prefix: /rating
    route:
    - destination:
        host: rating
        port:
          number: 5007
  - match:
    - uri:
        prefix: /config/
    - uri:
        prefix: /config
    rewrite:
      uri: /
      authority: {{ .Values.hosts.idp }}
    route:
    - destination:
        host: idp
        port:
          number: 80
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: spa
        port:
          number: 80
---
