# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: "Ubuntu 16.04"

trigger:
  branches:
    include:
      - master
    exclude:
      - docs
  paths:
    include:
      - docs/*

steps:
  - checkout: self
  - script: yarn install --frozen-lockfile
    displayName: "Install Dependencies"
  - script: |
      yarn docs:build
      mkdir $HOME/site
      sudo apt-get update && sudo apt-get install rsync
      rsync -avzh docs/.vuepress/dist/ $HOME/site
    displayName: "Build"
  - script: |
      if [[ $(GITHUB_TOKEN) ]]; then
        REPOSITORY="https://thangchung:$(GITHUB_TOKEN)@github.com/vietnam-devs/coolstore-microservices.git"
        git config user.email thangchung@users.noreply.github.com
        git config user.name thangchung
        git remote set-url origin ${REPOSITORY}
        rm -rf docs/.vuepress/dist
        git checkout gh-pages
        rm -rf assets
        rsync -avzh $HOME/site/ .
        git add .
        git commit -m "Publish docs"
        git push origin gh-pages
      else
        echo "No GitHub token found! Skip publishing"
      fi
    displayName: "Publish"
