## https://github.com/helm/charts/blob/master/stable/redis/values.yaml

image:
    repository: bitnami/redis
    tag: latest
    pullPolicy: IfNotPresent

cluster:
    enabled: true
    slaveCount: 1

usePassword: false

# Redis port
redisPort: 6379

master:
    service:
        ##  Redis Master Service type
        type: ClusterIP
        port: 6379