# migration
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration-v1
  namespace: coolstore
spec:
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
      - name: migration
        image: vndg/migration-data-v3:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ConnectionStrings__shoppingcart
          value: Data Source=sqlserver,1433;Initial Catalog=ShoppingCartDb;User Id=sa;Password=P@ssw0rd;MultipleActiveResultSets=True;
        - name: ConnectionStrings__productcatalog
          value: Data Source=sqlserver,1433;Initial Catalog=ProductCatalogDb;User Id=sa;Password=P@ssw0rd;MultipleActiveResultSets=True;
        - name: ConnectionStrings__inventory
          value: Data Source=sqlserver,1433;Initial Catalog=InventoryDb;User Id=sa;Password=P@ssw0rd;MultipleActiveResultSets=True;
      restartPolicy: Never
