apiVersion: v1
kind: Service
metadata:
  name: backoffice
  namespace: {{ .Release.Namespace }}
  labels:
    app: backoffice
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: backoffice
---
