apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: {{ .Release.Namespace }}
  labels:
    app: cart
spec:
  ports:
  - name: grpc
    port: {{ .Values.cartSettings.Port }}
    targetPort: {{ .Values.cartSettings.Port }}
    protocol: TCP
  selector:
    app: cart
---
