apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: {{ .Release.Namespace }}
  labels:
    app: catalog
spec:
  ports:
  - name: grpc
    port: {{ .Values.catalogSettings.Port }}
    targetPort: {{ .Values.catalogSettings.Port }}
    protocol: TCP
  selector:
    app: catalog
---
