apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: {{ .Release.Namespace }}
  labels:
    app: inventory
spec:
  ports:
  - port: {{ .Values.inventorySettings.Port }}
    targetPort: {{ .Values.inventorySettings.Port }}
    protocol: TCP
    name: http
  selector:
    app: inventory
---
