apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-v1
  namespace: {{ .Release.Namespace }}
  labels:
    app: inventory
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
      version: v1
  template:
    metadata:
      labels:
        transcode: http
        app: inventory
        version: v1
    spec:
      containers:
      - name: inventory
        image: {{.Values.image.imageRegistry}}/cs-inventory-service:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: Hosts__Local__Host
          value: {{ .Values.inventorySettings.Host }}
        - name: Hosts__Local__Port
          value: {{ .Values.inventorySettings.Port | quote }}
        - name: Features__EfCore__MySqlDb__FQDN
          value: {{ .Values.inventorySettings.MySqlDbFQDN }}
        - name: Features__EfCore__MySqlDb__Password
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: MySqlDbPassword
        ports:
        - containerPort: {{ .Values.inventorySettings.Port }}
        readinessProbe:
          initialDelaySeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.inventorySettings.Port }}"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.inventorySettings.Port }}"]
        # resources:
        #   requests:
        #     cpu: 70m
        #     memory: 128Mi
        #   limits:
        #     cpu: 250m
        #     memory: 256Mi
---
