apiVersion: v1
kind: Service
metadata:
  name: mymongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mymongodb
spec:
  ports:
  - port: 27017
    name: mongo
  selector:
    app: mymongodb
---
