apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysqldb
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysqldb
---
