apiVersion: v1
kind: Service
metadata:
  name: rating
  namespace: {{ .Release.Namespace }}
  labels:
    app: rating
spec:
  ports:
  - name: grpc
    port: {{ .Values.ratingSettings.Port }}
    targetPort: {{ .Values.ratingSettings.Port }}
    protocol: TCP
  selector:
    app: rating
---
