apiVersion: v1
kind: Service
metadata:
  name: spa
  namespace: {{ .Release.Namespace }}
  labels:
    app: spa
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spa
---
