version: '3'
services:  
  webapi:
    image: ivanpaulovich/clean-architecture-manga
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
        - 5500:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Development