# https://istio.io/docs/tasks/telemetry/kiali/
# https://github.com/istio/istio/issues/11742
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  username: YWRtaW4=
  passphrase: YWRtaW4=
